// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Infrastructure.Context;

namespace WebApplication.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication.Core.Domain.Portfolio", b =>
                {
                    b.Property<string>("ISINCode")
                        .HasMaxLength(12);

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<decimal>("MarketValue")
                        .HasColumnType("decimal(16 ,2)");

                    b.HasKey("ISINCode", "Date");

                    b.HasAlternateKey("Date", "ISINCode");

                    b.ToTable("Portfolios");
                });

            modelBuilder.Entity("WebApplication.Core.Domain.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("char(2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<decimal>("MarketValue")
                        .HasColumnType("decimal(16 ,2)");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<DateTime?>("PortfolioDate");

                    b.Property<string>("PortfolioISINCode");

                    b.Property<int?>("PositionTypeId");

                    b.Property<double>("StorePercentage");

                    b.HasKey("Id");

                    b.HasIndex("PositionTypeId");

                    b.HasIndex("PortfolioISINCode", "PortfolioDate");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("WebApplication.Core.Domain.PositionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("PositionTypes");
                });

            modelBuilder.Entity("WebApplication.Core.Domain.Position", b =>
                {
                    b.HasOne("WebApplication.Core.Domain.PositionType")
                        .WithMany("Positions")
                        .HasForeignKey("PositionTypeId");

                    b.HasOne("WebApplication.Core.Domain.Portfolio")
                        .WithMany("Positions")
                        .HasForeignKey("PortfolioISINCode", "PortfolioDate");
                });
#pragma warning restore 612, 618
        }
    }
}
